### ISSUE TITLE
Crashes if no network connection

### ISSUE THREAD

**Issue by rohanorton** [rohanorton/episoder#6]
Attempted to use on work network which blocks DNS requests and the app crashes with following error:
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
```

**Comment by rohanorton** [comment]
fixed.
